# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14630eff9384716b22f24a2b286edeeaeb05786c07ed6521262f4a9bec3a544e9311fa399d28c48d8db4bdbb37b6565d37996934c96c460b79352d56e1860680

test:
  secret_key_base: 011732f4cf894c48d4a2d71cca139a09f1d8ded45395c216c04fae847ff7615262baece8f3e2baac59d28cc2f8ff2560d96dced5d5504853a71ebd1bb95a31f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
